dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install mypy pyflakes jupyter
script:
  - pip install --editable `pwd`
  - cd tests; make install-rclone-deb test
